const productTypes = {
  GET_ALL_PRODUCTS_START: 'product/GET_ALL_PRODUCTS_START',
  GET_ALL_PRODUCTS_SUCCESS: 'product/GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'product/GET_ALL_PRODUCTS_FAILURE',
};

export default productTypes;
